require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'config/environments/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/homeworks_controller.rb'
    - 'app/controllers/notes_controller.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/helpers/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/homeworks_spec.rb'

RSpec/ExampleLength:
  Max: 8

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods