 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/homeworks", type: :request do

  # Homework. As you add validations to Homework, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /show" do
    it "renders a successful response" do
      homework = Homework.create! valid_attributes
      get homework_url(homework)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      homework = Homework.create! valid_attributes
      get edit_homework_url(homework)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Homework" do
        expect {
          post homeworks_url, params: { homework: valid_attributes }
        }.to change(Homework, :count).by(1)
      end

      it "redirects to the created homework" do
        post homeworks_url, params: { homework: valid_attributes }
        expect(response).to redirect_to(homework_url(Homework.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Homework" do
        expect {
          post homeworks_url, params: { homework: invalid_attributes }
        }.to change(Homework, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post homeworks_url, params: { homework: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested homework" do
        homework = Homework.create! valid_attributes
        patch homework_url(homework), params: { homework: new_attributes }
        homework.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the homework" do
        homework = Homework.create! valid_attributes
        patch homework_url(homework), params: { homework: new_attributes }
        homework.reload
        expect(response).to redirect_to(homework_url(homework))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        homework = Homework.create! valid_attributes
        patch homework_url(homework), params: { homework: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested homework" do
      homework = Homework.create! valid_attributes
      expect {
        delete homework_url(homework)
      }.to change(Homework, :count).by(-1)
    end

    it "redirects to the homeworks list" do
      homework = Homework.create! valid_attributes
      delete homework_url(homework)
      expect(response).to redirect_to(homeworks_url)
    end
  end
end
